import React from 'react';
import type { Metadata } from "next"

interface Props {
  
}

export const metadata: Metadata = {
  title: {
    absolute: "register", // register : مثلا برای برخی صفحات نیاز داریم تمپلیت توی اون صفحه اونطوری نوشته نشه توی این شرایط ما از ابسلوت استفاده میکنیم 
  },
  description: "Generated by Leach Shop",
};

const Register = (props: Props) => {
  return (
    <div className='text-5xl'>Register</div>
  );
};

export default Register;