import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import Layout from "@/Components/layout/Layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Leach Mob Shop",
//   description: "Generated by Leach Mob Shop",
// };
export const metadata: Metadata = {
  title: {
    default: "Leach shop", // همون تاتیل صفحه هست توی تگ هد
    template: "%s | Leach shop", // چیزی هست که میخایم توی همه اسم تایتل ها ثابت باشه و چیزی که تغییر میکنه درصد اس هست
  },
  description: "Generated by Leach Shop",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Header />
          <div className="pt-20" />
        <Layout>
          {children}
        </Layout>
          <Footer />
      </body>
    </html>
  );
}
